### ISSUE TITLE
Błędy interpunkcyjne

### ISSUE THREAD

**Issue by Nessie-XII** [Kochanowski-js/kochanowski.js#21]
Azaliż sprawdziliście Mości Państwo interpunkcję w ostatnim wydaniu Waszego jakże pięknego języka programowania? Albowiem ja, czytając informacje o ostatnim wydaniu, ku mojemu przerażeniu ujrzałam pomyłki niewybaczalne. W sekcji "Future releases" oszałamiający jest brak odpowiedniej interpunkcji. Jest to haniebne i uważam, że powinno zostać naprawione natychmiastowo. Po każdym wyliczeniu brakuje średnika i kropki na końcu.
![bledy_haniebne](https://github.com/Kochanowski-js/kochanowski.js/assets/173301863/14c1e155-1b92-40e4-8547-57e4499a5df5)

**Comment by CheryX** [comment]
Czcigodna Czytelniczko,

Zespół pisarzy KPL jest niezmiernie wdzięczny za zwrócenie naszej uwagi na te nieakceptowalne błędy interpunkcyjne w najnowszym wydaniu naszego języka programowania. Przepraszamy za wszelkie niedogodności, jakie mogły wyniknąć z tych przeoczeń.

Rzeczywiście, brak średników oraz kropek w sekcji "Future releases" jest niedopuszczalny i niezgodny z naszymi standardami. Natychmiast przystąpimy do naprawienia tych uchybień, aby przyszłe wydania były wolne od takich błędów.

Dziękujemy za Państwa czujność i konstruktywną krytykę. Państwa troska o jakość naszego dzieła jest dla nas nieoceniona.

Z wyrazami szacunku,
Zespół Programistów
